### ISSUE TITLE
Windows platform broken after #966

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#973]
After #966 build of samples/win32 fails:
```
KtFile: MessageBox.kt
src\main\kotlin\MessageBox.kt:4:5: error: unresolved reference: MessageBoxW
    MessageBoxW(null, "Konan говорит:\nЗДРАВСТВУЙ МИР!\n",
    ^
src\main\kotlin\MessageBox.kt:5:31: error: unresolved reference: MB_YESNOCANCEL
            "Заголовок окна", MB_YESNOCANCEL or MB_ICONQUESTION)
                              ^
src\main\kotlin\MessageBox.kt:5:49: error: unresolved reference: MB_ICONQUESTION
            "Заголовок окна", MB_YESNOCANCEL or MB_ICONQUESTION)
                                                ^
```

**Comment by olonho** [comment]
Shall be fixed with 1ce4e722e80a92aaf6d276bc57bdbe2a3254f212

**Comment by msink** [comment]
Ok, seems fixed now.

**Comment by msink** [comment]
Well, still not fixed.
6f43b6b does not compile:
```
_GdipFlat-build\kotlin\platform\gdiplus\gdiplus.kt:57:25: error: unresolved reference: SHORT
import platform.windows.SHORT
                        ^
_GdipFlat-build\kotlin\platform\gdiplus\gdiplus.kt:59:25: error: unresolved reference: ULONG
import platform.windows.ULONG                                                                                     17:43
                        ^
_GdipFlat-build\kotlin\platform\gdiplus\gdiplus.kt:60:25: error: unresolved reference: ULONGVar
import platform.windows.ULONGVar
                        ^
```

**Comment by olonho** [comment]
Guess gdiplus.kt is something not in K/N repo. Likely in your code you shall use import platform.posix.SHORT

**Comment by msink** [comment]
That ```gdiplus.kt``` is generated by ```cinerop``` tool from ```gdiplus.def```

**Comment by olonho** [comment]
Yes, but maybe you misspelled deps (i.e. depends = posix windows)

**Comment by msink** [comment]
```
depends = windows posix
package = platform.gdiplus
headers = wtypes.h gdiplus/gdiplus.h
headerFilter = gdiplus/**
compilerOpts = -DUNICODE
linkerOpts = -lgdiplus
```
Same error.

**Comment by msink** [comment]
```
depends = posix windows
package = platform.gdiplus
headers = wtypes.h gdiplus/gdiplus.h
headerFilter = gdiplus/**
compilerOpts = -DUNICODE
linkerOpts = -lgdiplus
```
Same.

**Comment by olonho** [comment]
Check 043e6c54cacec60cf4a8089f1b01901461383777 - it includes gdiplus.def file.

**Comment by msink** [comment]
Ok, thanks.
