### ISSUE TITLE
Gradle-plugin "org.jetbrains.kotlin.native" is not working with Gradle >= 5.2

### ISSUE THREAD

**Issue by Tapchicoma** [JetBrains/kotlin-native#2916]
Using latest "org.jetbrains.kotlin.native" version `1.3.31` with Gradle >= `5.2` fails with following stacktrace:
```
Caused by: java.lang.NoSuchMethodError: org.gradle.language.nativeplatform.internal.DefaultNativeComponent.<init>(Lorg/gradle/api/internal/file/FileOperations;)V
        at org.jetbrains.kotlin.gradle.plugin.experimental.internal.AbstractKotlinNativeComponent.<init>(AbstractKotlinNativeComponent.kt:58)
        at org.jetbrains.kotlin.gradle.plugin.experimental.internal.KotlinNativeMainComponent.<init>(KotlinNativeMainComponent.kt:46)
        at org.jetbrains.kotlin.gradle.plugin.experimental.internal.KotlinNativeMainComponent_Decorated.<init>(Unknown Source)
        at org.gradle.internal.instantiation.AsmBackedClassGenerator.newInstance(AsmBackedClassGenerator.java:153)
        at org.gradle.internal.instantiation.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:363)
        at org.gradle.internal.instantiation.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:48)
        ... 161 more
```

Seems in https://github.com/JetBrains/kotlin-native/blob/270a53ac8b953840763c23749c5998e8a17effcd/tools/kotlin-native-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/experimental/internal/AbstractKotlinNativeComponent.kt#L58 `DefaultNativeComponent` constructor was changed to have `ObjectFactory` as a parameter instead of `FileOperations`: https://github.com/gradle/gradle/blob/648f918719a845b79cc1dec3ee2940cb48c16aaa/subprojects/language-native/src/main/java/org/gradle/language/nativeplatform/internal/DefaultNativeComponent.java#L35

Related commits in Gradle:
- https://github.com/gradle/gradle/commit/747c4eecd87a87b3e1294f60edec7b3ad26e9c27#diff-4e84b52e1e92680118a27a6305835720
- https://github.com/gradle/gradle/commit/b036a8835c7b900a70a4f369e6e9feb2d2926d53#diff-4e84b52e1e92680118a27a6305835720

Also I think that native plugin should not use Gradle internal classes, that are not supposed to have stable API.

**Comment by Tapchicoma** [comment]
@artdfel what is the solution to this problem?

**Comment by artdfel** [comment]
Currently, this plugin is deprecated. It won't be updated anymore after 1.3.50. We recommend you to stop working with it and go for the `kotlin-multiplatform` plugin, as it comes to be our main Gradle plugin.
