### ISSUE TITLE
1.3.60-eap-23 method_invoke Too many arguments

### ISSUE THREAD

**Issue by tsakoyan** [JetBrains/kotlin-native#3464]
I'm getting 
`Too many arguments for @CCall public external fun method_invoke(): Unit defined in platform.objc`
I need to explicitly define it like
`@SymbolName("method_invoke")
external fun method_invoke(receiver: ObjCClass, m: CPointer<objc_method>?): NativePtr`
and follow it up with `interpretObjCPointerOrNull`.
Maybe it's related to b393e4f900d4e628a6e1c4f9c16a9362f2277395

**Comment by artdfel** [comment]
Hello! Can you please provide a reproducer? Also, do I understand correctly that on 1.3.50 this was working?

**Comment by idstein** [comment]
Yes, it is working on 1.3.50. Example:

```
val receiver = NSObject()
val method: Method
val debugNSString = method_invoke(receiver, method)
```

The cinterop in 1.3.60_eap23 generates `fun method_invole(): Unit` bridge instead of `fun method_invoke(receiver: ObjCObject?, method: Method, vararg arguments: Any): Any`

**Comment by olonho** [comment]
Have you seen https://mikeash.com/pyblog/objc_msgsends-new-prototype.html?

**Comment by idstein** [comment]
Thanks a lot for the clarification. That really helped a lot to understand the circumstances of the changed API by Apple.
I think we can close this ticket as this is as designed & expected.

**Comment by olonho** [comment]
Restored old signatures with #3470, as they seems to make more sense and closing the issue.
