### ISSUE TITLE
iOS/XCode compilation error starting with grade native plugin 0.7-dev-1613

### ISSUE THREAD

**Issue by epool** [JetBrains/kotlin-native#1660]
I'm trying to run the calculator project from [this repo](https://github.com/JetBrains/kotlin-native-calculator-sample/issues/new) and it works fine with the current [0.7-dev-1407](https://github.com/JetBrains/kotlin-native-calculator-sample/blob/master/gradle.properties#L1) used version in the repo and until [0.7-dev-1587](https://dl.bintray.com/jetbrains/kotlin-native-dependencies/org/jetbrains/kotlin/kotlin-native-gradle-plugin/0.7-dev-1587/), **BUT** if I upgrade to a newer version of the grade native plugin, starting with [0.7-dev-1613](https://dl.bintray.com/jetbrains/kotlin-native-dependencies/org/jetbrains/kotlin/kotlin-native-gradle-plugin/0.7-dev-1613/) and do a full clean of the XCode project(`Option` + `Command` + `Shift` + `K`) I start to see this error:
```
~/Library/Developer/Xcode/DerivedData/calculator-exqeuqrtvkznonceltwlrlodnkiw/Build/Products/Debug-iphonesimulator/KotlinArithmeticParser.framework: bundle format unrecognized, invalid, or unsuitable
Command /usr/bin/codesign failed with exit code 1
```
And this is because 

```
~/Library/Developer/Xcode/DerivedData/calculator-exqeuqrtvkznonceltwlrlodnkiw/Build/Products/Debug-iphonesimulator/KotlinArithmeticParser.framework
```

is being empty and the framework is being built in the same directory of the XCode project(`~/kotlin-native-calculator-sample/ios/build/`).

If I manually copy this
```
~/kotlin-native-calculator-sample/ios/build/konan/bin/ios_x64/KotlinArithmeticParser.framework
``` 
and paste it at 
```
~/Library/Developer/Xcode/DerivedData/calculator-exqeuqrtvkznonceltwlrlodnkiw/Build/Products/Debug-iphonesimulator/KotlinArithmeticParser.framework
``` 
and I retry the build, it works.

Looks like `0.7-dev-1587` and below used to do the build in the correct directory(`~/Library/Developer/Xcode/DerivedData/calculator-exqeuqrtvkznonceltwlrlodnkiw/Build/Products/Debug-iphonesimulator/`) and starting with `0.7-dev-1613` it does the build in the current directory(`~/kotlin-native-calculator-sample/ios/build/`). This could be related to #1438 .

Sorry if I am missing some specif configuration, but this used to work out of the box as I mentioned before. In advance thanks!

**Comment by subprogram** [comment]
I have the same issue for my project - "No such module" after clean build. I've tested plugin versions 0.7-dev-1613, 0.8-dev-2179 and 0.7.1-rc1-2320. 
On 0.7-dev-1587 this issue isn't reproduced.

**Comment by ilmat192** [comment]
Right, since v0.6.2 the Gradle plugin uses project properties instead of env variables to obtain an output path for artifacts built. So settings of the XCode project should be updated if you use a new version. 

I've updated the project to v0.7.1 and fix these settings (https://github.com/JetBrains/kotlin-native-calculator-sample/commit/88b537480d8dd44f41e46998dcc1a2df00916f7c).
