### ISSUE TITLE
Zephyr example doesn't build with version 1.10.99/0.9.2

### ISSUE THREAD

**Issue by turbinenreiter** [JetBrains/kotlin-native#1379]
The Zephyr sample doesn't build with Zephyr 1.10.99 and SDK 0.9.2.

```
~/Projects/kotlin-native/samples/zephyr/src/main.kt:22:16: error: unresolved reference: LED0_GPIO_PORT
    val port = LED0_GPIO_PORT
                    ^
```

**Comment by msink** [comment]
Works for me, on Linux and Windows hosts.
But I do not use Zephyr SDK, just plain [GNU Arm Embedded Toolchain](https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads)

**Comment by alexander-gorshenev** [comment]
@turbinenreiter Can you run the `build.sh` script as `bash -x buld.sh` and show us the output?

**Comment by turbinenreiter** [comment]
This is the output:
https://gist.github.com/turbinenreiter/50a1c822fb8bfc96f32c5d146c0bdcc2

I'm just trying to build as intended with inte included build script - when we figure this out, we should put it in a README file - it's not exactly clear what prerequisites you need. I assumed I need the Zephyr SDK, but apparently I don't?

**Comment by alexander-gorshenev** [comment]
@turbinenreiter Thanks for the log. And another thind we'd like to take a look at now is the output of the following command: ```klib contents /home/plam/Projects/kotlin-native/samples/zephyr/c_interop/platforms/build/stm32f4_disco``` , where `klib` is the utility in the `bin` directory of your kotlin/native installation. Beware, it can be tens of thousands of lines.

**Comment by alexander-gorshenev** [comment]
@turbinenreiter And the most important thing: what is the compiler you are using? Is it some late master, a release or just a so and so commit in the git history?

**Comment by alexander-gorshenev** [comment]
@turbinenreiter Nono, don't use PIN for PORT. that wouldn't work. Judging from the bash log you gave me, this is not the latest release. 

Grab the brand new 6.1 release from here: https://github.com/JetBrains/kotlin-native/releases/tag/v0.6.1 and things should work as expected. Let us know your progress.

**Comment by turbinenreiter** [comment]
... I forgot to update the path in my bashrc ...
:man_facepalming: 

Works perfectly now!

**Comment by alexander-gorshenev** [comment]
Great! Have fun. 

Oh, wait! Is it blinking???

**Comment by turbinenreiter** [comment]
It builds - the actual board is still being shipped :D

**Comment by turbinenreiter** [comment]
@alexander-gorshenev could you maybe give me some pointers about how to add another of the zephyr supported boards as target? I'm digging around in the commit history to find the necessary changes.

**Comment by alexander-gorshenev** [comment]
As long as the same gcc arm toolchain works for you, you can provide a new platform definition file. But as Mike points out, as of now, you still need to recompile the kotlin/native from source.  And you will probably need to tweak the `samples/zephyr/c_interop/platforms/$BOARD.sh` for the proper set of headers. This is all still being work on now, so things can change in the upcoming releases.

**Comment by msink** [comment]
And if your board is Cortex-M4 - you can just use `-target zephyr_stm32f4_disco` for kotlin part and <yourrealboard> for zephyr part.
There really nothing board-specific in kotlin runtime, just arch-specific.

**Comment by turbinenreiter** [comment]
I'm using a STM32F412 - the arch is the same, but the memory is different, the pinout is different.

```
konanc $DIR/src/main.kt \
        -target zephyr_$BOARD \
        -r $DIR/c_interop/platforms/build \
        -l $BOARD \
        -opt -g -o $DIR/build/kotlin/program
```

Should this maybe be split up?
i.e.:
`
-target_rtos zephyr
-target_arch cortex-m4
-target_mcu stm32f407 <- for linking
-targt_board stm32f4_disco <- for board library, pinout
`

I'll have to keep reading and understand the build system better.

And thanks for the support, I hope to pay it back by adding another board as target.
