### ISSUE TITLE
String to LPCWSTR (CPointer<WCHARVar /* = ShortVarOf<WCHAR /* = Short */> */>) conversation problem

### ISSUE THREAD

**Issue by cqjjjzr** [JetBrains/kotlin-native#1650]

**Comment by olonho** [comment]
Better write it like that (so that memory doesn't leak):
```
import platform.windows.*
import kotlinx.cinterop.*

fun main(args: Array<String>): Unit = memScoped {
    val wndclass = alloc<WNDCLASS>().apply {
        lpszClassName = "helloWin32".wcstr.ptr
    }
    MessageBoxW(null, "Class is ${wndclass.lpszClassName}\n",
            "Title", MB_YESNOCANCEL or MB_ICONQUESTION)}

```
It works for me as expected, and memory is freed once we leave `main()`.

**Comment by cqjjjzr** [comment]
But it doesn't compile...
```
src\main\kotlin\hello.kt:8:44: error: unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public val <T : CPointed> ???.ptr: CPointer<???> defined in kotlinx.cinterop
        lpszClassName = "helloWin32".wcstr.ptr
```
Is there anything i missed?

**Comment by olonho** [comment]
Which version of Kotlin/Native do you use? Shall work with 0.7

**Comment by cqjjjzr** [comment]
0.7 I think...

**Comment by cqjjjzr** [comment]
I find the problem....
The type of `wcstr` property is `CValues<ShortVar>` which is not a "CPointed" or "CxxxxVar" that has `ptr` property, but @olonho as you said it should work. so is the problem in the type of the `wcstr` or in the receiver type of `ptr` property? Is there any library I missed? Thanks!

**Comment by olonho** [comment]
Hmm, does my code snippet compiles? What is `konanc -version` output?

**Comment by cqjjjzr** [comment]
It compiles, but I think I need to place the string to the global heap. Because I need to expose the pointer to the WIN32. codes below fails:
```kotlin
import platform.windows.*
import kotlinx.cinterop.*

val currentHInstance = GetModuleHandleW(null)

fun wndProc(hwnd: HWND?, msg: UINT, p1: WPARAM, p2: LPARAM): LRESULT {
    return 0
}

fun main(args: Array<String>): Unit = memScoped {
    val wndclass = alloc<WNDCLASS>().apply {
        lpszClassName = "helloWin32".wcstr.ptr
        style = CS_HREDRAW or CS_VREDRAW
        lpfnWndProc = staticCFunction(::wndProc)
        hInstance = currentHInstance
    }
    if (RegisterClassW(wndclass.ptr) == 0.toShort())
        return println("register failed")
    val hwnd = CreateWindowExW(
            0,
            "helloWin32",
            "Test Window",
            CS_HREDRAW or CS_VREDRAW,
            50, 50,
            500, 500,
            null, null, currentHInstance, null
    ) ?: return println("create failed")
    ShowWindow(hwnd, SW_SHOW)
    UpdateWindow(hwnd)
}

```
fails when creating, I think the class name from the WNDCLASS didn't passed properly to the C world.
