### ISSUE TITLE
Cannot compile to wasm on Windows with 0.6.1

### ISSUE THREAD

**Issue by boyanio** [JetBrains/kotlin-native#1387]
Hello. I decided to play around with `kotlin.math` in WebAssembly in 0.6.1, but I get an error when trying to compile my test program. It works fine with 0.6. The error is:

```
[[object_alias:]]:
==========
.section        .init_array,"aw",@init_array
        .p2align        2
        .int32  _G
==========

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
error: compilation failed: The C:\Users\abc\.konan\dependencies\target-toolchain-1-mingw-wasm/bin/s2wasm command returned non-zero exit code: 3.

 * Source files: test.kt
 * Compiler version info: Konan: EAP 0.6.1.0 / Kotlin: 1.2.40
 * Output kind: PROGRAM

exception: org.jetbrains.kotlin.konan.KonanExternalToolFailure: The C:\Users\abc\.konan\dependencies\target-toolchain-1-mingw-wasm/bin/s2wasm command returned non-zero exit code: 3.
        at org.jetbrains.kotlin.konan.exec.Command.handleExitCode(ExecuteCommand.kt:100)
        at org.jetbrains.kotlin.konan.exec.Command.execute(ExecuteCommand.kt:66)
        at org.jetbrains.kotlin.backend.konan.LinkStage.runTool(LinkStage.kt:51)
        at org.jetbrains.kotlin.backend.konan.LinkStage.targetTool(LinkStage.kt:76)
        at org.jetbrains.kotlin.backend.konan.LinkStage.bitcodeToWasm(LinkStage.kt:109)
        at org.jetbrains.kotlin.backend.konan.LinkStage.access$bitcodeToWasm(LinkStage.kt:29)
        at org.jetbrains.kotlin.backend.konan.LinkStage$linkStage$1.invoke(LinkStage.kt:222)
        at org.jetbrains.kotlin.backend.konan.LinkStage$linkStage$1.invoke(LinkStage.kt:29)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:140)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:119)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:139)
        at org.jetbrains.kotlin.backend.konan.LinkStage.linkStage(LinkStage.kt:218)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$5.invoke(KonanDriver.kt:109)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$5.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:140)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:119)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:139)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:108)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:61)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:39)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:108)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:70)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:157)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:148)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:183)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:174)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:176)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:188)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:27)
```
I tried removing the `.konan` folder, but after downloading the dependencies again, it still fails. My program looks like this:

```
@Used
public fun test(): Int {
  return 5
}
```

**Comment by alexander-gorshenev** [comment]
@boyanio Could you give the exact compiler command line you use. I can reproduce the `s2wasm` issue passing the assembly snippet to `s2wasm`, but I can not reproduce the issue passing the kotlin snippet to `konanc`.

**Comment by boyanio** [comment]
I used the following command:

`konanc test.kt -target wasm32 -o out/test.wasm -verbose`

**Comment by alexander-gorshenev** [comment]
@boyanio I can't reproduce the problem. 

Neither with 0.6.1, nor with the current master. Nether the .kt snippet above, nor the https://github.com/boyanio/wasm-wheel/blob/master/src/langs/kotlin/wheel-part.kt

Can you give me the complete .s file the `s2wasm` tool chokes on?

**Comment by boyanio** [comment]
@alexander-gorshenev I did some more research and I believe I've found the issue. As you say, it works pretty fine with my `test.kt` and my original `wheel-part.kt`. The issue comes when one specifies an output file with dash in the name.

This works fine:
`konanc wheel-part.kt -target wasm32 -o wheelpart.wasm -verbose`

This returns the error:
`konanc wheel-part.kt -target wasm32 -o wheel-part.wasm -verbose`

**Comment by alexander-gorshenev** [comment]
Ah, that makes sense. I think we can escape the names in Kotlin/Native somehow.

**Comment by alexander-gorshenev** [comment]
If you really need the output file name to contain the dash, as a workaround, you can override  the module name (auto-deduced from the file name by default) with the `-module_name` flag. `-o bar-qux -module_name barqux`.
