### PR TITLE
 Unify interop with Objective-C in both directions

### PR DESCRIPTION
**Pull request by SvyatoslavScherbina**

### CODE REVIEW

File: runtime/src/main/cpp/ObjCExport.mm [hunk 1]
```diff
@@ -214,6 +225,28 @@ - (instancetype)copyWithZone:(NSZone *)zone {
...
+  auto numBytes = str->array()->count_ * sizeof(KChar);
+
+  if (str->permanent()) {
+    return [[[NSString alloc] initWithBytesNoCopy:utf16Chars
+        length:numBytes
+        encoding:NSUTF16LittleEndianStringEncoding
+        freeWhenDone:NO] autorelease];
+  } else {
+    // TODO: consider making NSString subclass to avoid copying here.
+
```
Comment (olonho) [inline runtime/src/main/cpp/ObjCExport.mm]: Extra space.

File: backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/llvm/CodeGenerator.kt [hunk 2]
```diff
@@ -85,18 +87,19 @@ internal class CodeGenerator(override val context: Context) : ContextUtils {
...
+        return typeInfoValue(constructedClass)
     }
 
     fun generateLocationInfo(locationInfo: LocationInfo): DILocationRef? {
         return LLVMCreateLocation(LLVMGetModuleContext(context.llvmModule), locationInfo.line, locationInfo.line, locationInfo.scope)
     }
 
+    val objCDataGenerator = when (context.config.target) {
+        KonanTarget.IOS_ARM64, KonanTarget.IOS_X64, KonanTarget.MACOS_X64 -> ObjCDataGenerator(this)
+        else -> null
```
Comment (PavelPunegov) [inline backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/llvm/CodeGenerator.kt]: Why do you return null instead of throwing an exception, e.g. IllegalStateException with description about incorrect target

File: Interop/StubGenerator/src/main/kotlin/org/jetbrains/kotlin/native/interop/gen/ObjCStubs.kt [hunk 3]
```diff
@@ -403,13 +427,10 @@ open class ObjCClassOrProtocolStub(
...
         container,
-        isMeta = false
+        metaContainerStub = object : ObjCContainerStub(stubGenerator, container, metaContainerStub = null) {}
 ) {
-    private val metaClassStub =
-            object : ObjCContainerStub(stubGenerator, container, isMeta = true) {}
-
     override fun generate(context: StubGenerationContext) =
-            metaClassStub.generate(context) + "" + super.generate(context)
+            metaContainerStub!!.generate(context) + "" + super.generate(context)
```
Comment (olonho) [inline Interop/StubGenerator/src/main/kotlin/org/jetbrains/kotlin/native/interop/gen/ObjCStubs.kt]: Why not interpolation?

File: Interop/StubGenerator/src/main/kotlin/org/jetbrains/kotlin/native/interop/gen/ObjCStubs.kt [hunk 4]
```diff
@@ -585,3 +606,22 @@ private fun NativeCodeBuilder.genMethodImp(
...
+        stubGenerator: StubGenerator,
+        nativeBacked: NativeBacked,
+        protocol: ObjCProtocol
+): String {
+    val functionName = "kniprot_" + stubGenerator.pkgName.replace('.', '_') + stubGenerator.nextUniqueId()
+
+    val builder = NativeCodeBuilder(stubGenerator.simpleBridgeGenerator.topLevelNativeScope)
+
+    with(builder) {
+        out("Protocol* $functionName() {")
```
Comment (olonho) [inline Interop/StubGenerator/src/main/kotlin/org/jetbrains/kotlin/native/interop/gen/ObjCStubs.kt]: Multiline string?

File: backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/llvm/CodeGenerator.kt (hunk 2 above)
Comment (SvyatoslavScherbina) [reply backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/llvm/CodeGenerator.kt]: Because this code works for all targets, and having `null` on target not supporting Objective-C interop is the intentional behaviour here.

File: Interop/StubGenerator/src/main/kotlin/org/jetbrains/kotlin/native/interop/gen/ObjCStubs.kt (hunk 4 above)
Comment (SvyatoslavScherbina) [reply Interop/StubGenerator/src/main/kotlin/org/jetbrains/kotlin/native/interop/gen/ObjCStubs.kt]: `out` isn't supposed to take multiline strings.

File: backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/llvm/IrToBitcode.kt [hunk 5]
```diff
@@ -2226,36 +2300,24 @@ internal class CodeGeneratorVisitor(val context: Context, val lifetimes: Map<IrE
...
-            val classPointerGlobal = objCDeclarations.classPointerGlobal.llvmGlobal
-            val gen = functionGenerationContext
-
-            val storedClass = gen.load(classPointerGlobal)
+        return functionGenerationContext.getObjCClass(classDescriptor, currentCodeContext.exceptionHandler)
+    }
 
-            val storedClassIsNotNull = gen.icmpNe(storedClass, kNullInt8Ptr)
+    private fun genGetObjCProtocol(irClass: IrClass): LLVMValueRef {
+        // Note: this function will return the same for Obj-C protocol and corresponding meta-class.
```
Comment (olonho) [inline backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/llvm/IrToBitcode.kt]: the same result

File: backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/lower/InteropLowering.kt [hunk 6]
```diff
@@ -349,6 +340,29 @@ internal class InteropLoweringPart1(val context: Context) : IrBuildingTransforme
...
+            val overriddenMethodOfAny = method.allOverriddenDescriptors.firstOrNull {
+                it in methodsOfAny
+            }
+
+            if (overriddenMethodOfAny != null) {
+                val correspondingObjCMethod = when (method.name.asString()) {
+                    "toString" -> "'description'"
+                    "hashCode" -> "'hash'"
+                    "equals" -> "'isEqual:'"
+                    else -> "corresponding Objective-C method"
```
Comment (olonho) [inline backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/lower/InteropLowering.kt]: Not `throw Error()`?

File: backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/objcexport/ObjCExport.kt [hunk 7]
```diff
@@ -29,18 +31,50 @@ import org.jetbrains.kotlin.name.FqName
...
-        val namer = headerGenerator.namer
-        val mapper = headerGenerator.mapper
+            val namer = ObjCExportNamer(context, mapper)
+            objCCodeGenerator = ObjCExportCodeGenerator(codegen, namer, mapper)
+
+            generatedClasses = emptySet()
+            topLevelDeclarations = emptyMap()
+        }
+
+        objCCodeGenerator.emitRtti(generatedClasses = generatedClasses, topLevel = topLevelDeclarations)
```
Comment (olonho) [inline backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/objcexport/ObjCExport.kt]: Nice!

File: backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/lower/InteropLowering.kt (hunk 6 above)
Comment (SvyatoslavScherbina) [reply backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/lower/InteropLowering.kt]: Crashing while trying to report a compilation error seems to be very bad practice. Take into account that we don't have any tests for these compilation errors.

File: runtime/src/main/cpp/Memory.cpp [hunk 8]
```diff
@@ -838,6 +820,11 @@ void ObjHeader::destroyMetaObject(TypeInfo** location) {
     WeakReferenceCounterClear(meta->counter_);
     UpdateRef(&meta->counter_, nullptr);
   }
+
+#ifdef KONAN_OBJC_INTEROP
+  Kotlin_ObjCExport_releaseAssociatedObject(meta->associatedObject);
```
Comment (olonho) [inline runtime/src/main/cpp/Memory.cpp]: By convention we add `_` to the end of C++ field names, i.e. `associatedObject_`
