### ISSUE TITLE
Build fails on Zulu-9 using Gradle 4.3.1

### ISSUE THREAD

**Issue by russel** [JetBrains/kotlin-native#1057]
The build works fine using Gradle 4.3.1 on Zulu-8. However on Zulu-9:
```
|> gradle dist distPlatformLibs

> Task :shared:compileKotlin 
Using kotlin incremental compilation

w: /home/Checkouts/Git/Kotlin-Native/shared/src/main/kotlin/org/jetbrains/kotlin/konan/target/KonanTarget.kt: (19, 19): Parameter 'name' is never used

> Task :Interop:Runtime:compileKotlin 
Using kotlin incremental compilation

> Task :Interop:Runtime:compileCallbacksSharedLibraryCallbacksC FAILED
/home/Checkouts/Git/Kotlin-Native/Interop/Runtime/src/callbacks/c/callbacks.c:3:10: fatal error: 'jni.h' file not found
#include <jni.h>
         ^
1 error generated.


> Task :Interop:Indexer:compileClangstubsSharedLibraryClangstubsC FAILED
/home/Checkouts/Git/Kotlin-Native/Interop/Indexer/prebuilt/nativeInteropStubs/c/clangstubs.c:2:10: fatal error: 'jni.h' file not found
#include <jni.h>
         ^
1 error generated.



FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':Interop:Runtime:compileCallbacksSharedLibraryCallbacksC'.
> A build operation failed.
      C compiler failed while compiling callbacks.c.
  See the complete log at: file:///home/Checkouts/Git/Kotlin-Native/Interop/Runtime/build/tmp/compileCallbacksSharedLibraryCallbacksC/output.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':Interop:Indexer:compileClangstubsSharedLibraryClangstubsC'.
> A build operation failed.
      C compiler failed while compiling clangstubs.c.
  See the complete log at: file:///home/Checkouts/Git/Kotlin-Native/Interop/Indexer/build/tmp/compileClangstubsSharedLibraryClangstubsC/output.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
12 actionable tasks: 12 executed
```

**Comment by msink** [comment]
Java 9 ?

**Comment by russel** [comment]
Yes, I am just stacking issues for when Kotlin/Native tackles Java 9.

**Comment by olonho** [comment]
Does Kotlin/JVM works on Zulu ?

**Comment by russel** [comment]
@olonho Yes. Zulu is Azul's build of OpenJDK.

**Comment by olonho** [comment]
Shall be fixed with https://github.com/JetBrains/kotlin-native/pull/1274
