### ISSUE TITLE
Regression: Very slow and memory hungry linkTestDebugExecutableMacos

### ISSUE THREAD

**Issue by jurmous** [JetBrains/kotlin-native#3098]
After upgrading to 1.3.40 the `linkTestDebugExecutableMacos` task in my project crashes with `Compilation failed: GC overhead limit exceeded` It only works after giving it a heap of like 8 GB (higher than 6G at least)) while it could manage with way less before. Also the compile time goes up from like 2:30 minutes to around 10 minutes since the update.

I have included a CPU and memory profile (with the experimental jetbrains profiler) of the entire run. (Or are there more ways to help)

[Mem profile 52774 org.jetbrains.kotlin.cli.utilities.MainKt-started-22062019-115838.collapsed.zip](https://github.com/JetBrains/kotlin-native/files/3316741/Mem.profile.52774.org.jetbrains.kotlin.cli.utilities.MainKt-started-22062019-115838.collapsed.zip)

[CPU Profile 54334 org.jetbrains.kotlin.cli.utilities.MainKt-started-22062019-124809.collapsed.zip](https://github.com/JetBrains/kotlin-native/files/3316758/CPU.54334.org.jetbrains.kotlin.cli.utilities.MainKt-started-22062019-124809.collapsed.zip)

**Comment by SvyatoslavScherbina** [comment]
Does compiling with `-Xdisable-phases=Devirtualization,BuildDFG` option help?

**Comment by jurmous** [comment]
Yes that brings it back to the old compile times. Is there a way to set this in the gradle? 
Is this phase new? Or what is changed? Is there any way I can help to bring the time of that phase back to something normal?

**Comment by SvyatoslavScherbina** [comment]
> Is there a way to set this in the gradle?

Something like this performed for a target should help:
```
compilations.all {
    kotlinOptions {
        freeCompilerArgs += "-Xdisable-phases=Devirtualization,BuildDFG"
    }
}
```

> Is this phase new?

Yes.

> Is there any way I can help to bring the time of that phase back to something normal?

Not yet, but this can change once we start digging into this. Thank you for the report!

**Comment by jurmous** [comment]
Thanks! For now I will disable the phase.

**Comment by jurmous** [comment]
@SvyatoslavScherbina I have an issue with the tests from the subproject which were causing also this issue and are running after disabling the Devirtualization. Now the code throws:

```FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:macosTest'.
> Bad TCSM: unexpected node to close `macosTest`, expected `$testFunctionName`, stack: 
   - $path.TestClass
   - macosTest```

It seems to move to other tests if I comment out the test and if I isolate the test and to be tested code it seems to succeed. Is this a new issue or somehow affected by disabling these phases? What is TCSM?

**Comment by SvyatoslavScherbina** [comment]
This might be related: https://youtrack.jetbrains.com/issue/KT-32136

**Comment by jurmous** [comment]
@SvyatoslavScherbina It looks similar. Although it happens on tests which always succeeded (Still do on JVM) and don't fail in a separate new project. But I will continue discussion for that fail in mentioned issue.

**Comment by jurmous** [comment]
This issue is resolved in 1.3.50. With Devirtualization enabled it now runs smoothly and only adds a few seconds to total link time.

**Comment by raniejade** [comment]
I'm getting something similar but now for a `release` build. `debug` builds works fine (compile times are still terrible tho). The project is quite big tho (https://github.com/raniejade/godot-kotlin-demos) so it might be that as well.
