### ISSUE TITLE
Undefined symbol on iOS when using cocoapods interoperability

### ISSUE THREAD

**Issue by FrangSierra** [JetBrains/kotlin-native#3412]
Hello everyone,

I'm having some troubles using the current cocoapods interoperability with `FirebaseAuth` and `FirebaseCore` dependencies. Everything works on Android native and on both sharedModules(android and ios). 

However, when I'm trying to call my new `sharedmodule` methods from iOS code, the code itself is missing a lot of symbols that are already inside of the header.

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FIRAuth", referenced from:
      objc-class-ref in app(result.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

If I Import `_FIRAuth`,  all the dependencies needed inside the own `FirebaseAuth` and `FirebaseCore` frameworks start to be missed and showed as undefined symbols. Even importing all of them still not working properly. You can reproduce the error easily just downloading the project, executing the `build.sh` to generate the podspec dependencies and trying to execute the iosApplication.

The whole code can be found on this repository: https://github.com/minuscorp/kotlin-native-firebase

**Comment by kuuuurt** [comment]
Hello @FrangSierra. How were you able to resolve this issue? I've been having the same error ([issue here](https://github.com/JetBrains/kotlin-native/issues/3702)).

**Comment by FrangSierra** [comment]
Hello @kuuuurt ,

I was not able to fix it, so finally my team decided to drop the KTM idea and we made everything natively on both platforms.

Sorry @artdfel, after drop the idea I got forced to delete the repository for company copyright stuffs :( . However this still happening to other users, I will try to recover the repository and upload it again. Maybe new versions fix it already

**Comment by kuuuurt** [comment]
Thanks for the response. That's sad to hear. 

Unfortunately, it's not yet fixed. It doesn't work on 1.3.61. Hoping to get this fixed soon.
